# Run tests w/ pytest
language: python
python: "3.7"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install -r requirements.txt
install:
  - pip install .
script:
  - pytest
# Deploy to AWS Lambda
deploy:
  provider: lambda
  region: "us-east-1"
  role: "arn:aws:iam::491984534845:role/datascience-bot-travis-ci"
  runtime: "python3.7"
  handler_name: "lambda_function.lambda_handler"
  function_name: "datascience-bot-test"
  on:
    branch: "11/automate-lambda-deployments"
